module.exports = {
    major_anno : {
        LegendsNum : 10,
        Legends : [
            "cathe",
            "epidermal",
            "gut",
            "muscle",
            "neoblast",
            "Neural",
            "parenchymal",
            "pharynx",
            "protonephridia",
        ],
    },
    major_celltype : {
        LegendsNum :26,
        Legends : [
           "cathe_16",
           "cathe_17",
           "epidermal_19",
           "epidermal_2",
           "epidermal_4",
           "gut_0",
           "gut_1",
           "gut_6",
           "muscle",
           "neoblast",
           "Neural_18",
           "Neural_20",
           "Neural_21",
           "Neural_22",
           "Neural_23",
           "Neural_5",
           "parenchymal_10",
           "parenchymal_12",
           "parenchymal_13",
           "parenchymal_14",
           "parenchymal_3",
           "parenchymal_7",
           "parenchymal_8",
           "parenchymal_9",
           "pharynx",
           "protonephridia",
         ],
    },
};
